import Foundation

public enum SwiftParserAccessLevel: String, CaseIterable, Codable, Sendable {
    case `public`
    case `internal`
}

public enum SwiftParserConflictPolicy: String, CaseIterable, Codable, Sendable {
    /// Refuse generation when an ACTION cell still has multiple effective actions.
    case fail
    case preferShift
    case preferReduce
    case firstAction
}

public struct SwiftParserGenerationOptions: Hashable, Codable, Sendable {
    public var typeName: String
    public var accessLevel: SwiftParserAccessLevel
    public var conflictPolicy: SwiftParserConflictPolicy

    public init(
        typeName: String = "GeneratedParser",
        accessLevel: SwiftParserAccessLevel = .public,
        conflictPolicy: SwiftParserConflictPolicy = .fail
    ) {
        self.typeName = typeName
        self.accessLevel = accessLevel
        self.conflictPolicy = conflictPolicy
    }
}

public enum SwiftParserGenerationError: Error, LocalizedError, Sendable {
    case invalidTypeName(String)
    case unresolvedConflicts([String])

    public var errorDescription: String? {
        switch self {
        case .invalidTypeName(let name):
            "‘\(name)’ is not a valid Swift type name."
        case .unresolvedConflicts(let cells):
            "Parser generation requires deterministic ACTION cells. Resolve conflicts at \(cells.joined(separator: ", ")) or select an explicit conflict policy."
        }
    }
}

enum SwiftParserCodeGenerator {
    static func generate(
        grammar: ParsedGrammar,
        artifact: GrammarArtifact,
        options: SwiftParserGenerationOptions
    ) throws -> String {
        guard isValidIdentifier(options.typeName) else {
            throw SwiftParserGenerationError.invalidTypeName(options.typeName)
        }

        let conflicts = artifact.cells.filter { cell in
            cell.actions.count > 1 && cell.actions.contains { action in
                if case .goTo = action { return false }
                return true
            }
        }
        if options.conflictPolicy == .fail, !conflicts.isEmpty {
            throw SwiftParserGenerationError.unresolvedConflicts(
                conflicts.map { "I\($0.id.state.rawValue) on ‘\($0.id.symbol)’" }
            )
        }

        let access = options.accessLevel == .public ? "public " : ""
        let actionRows = artifact.cells.compactMap { cell -> String? in
            guard let action = selectedAction(in: cell, policy: options.conflictPolicy) else { return nil }
            return "        \(key(cell.id)): \(actionSource(action))"
        }.joined(separator: ",\n")
        let productions = artifact.productions.map {
            "        \($0.id.rawValue): Production(lhs: \(literal($0.lhs)), count: \($0.rhs.count))"
        }.joined(separator: ",\n")
        let rules = lexerRules(grammar).map {
            "        LexerRule(kind: \($0.kind.map(literal) ?? "nil"), pattern: \(literal($0.pattern)))"
        }.joined(separator: ",\n")
        return """
        // Generated by Grammar Workbench \(GrammarWorkbenchRelease.version).
        // Algorithm: \(artifact.algorithm.rawValue). Do not edit generated tables by hand.
        import Foundation

        \(access)enum \(options.typeName) {
            \(access)struct Token: Hashable, Sendable {
                \(access)let kind: String
                \(access)let lexeme: String
                \(access)let utf16Offset: Int

                \(access)init(kind: String, lexeme: String? = nil, utf16Offset: Int = 0) {
                    self.kind = kind
                    self.lexeme = lexeme ?? kind
                    self.utf16Offset = utf16Offset
                }
            }

            \(access)struct Node: Hashable, Sendable {
                \(access)let symbol: String
                \(access)let children: [Node]
                \(access)let lexeme: String?
                \(access)let utf16Offset: Int?

                \(access)init(symbol: String, children: [Node] = [], lexeme: String? = nil, utf16Offset: Int? = nil) {
                    self.symbol = symbol
                    self.children = children
                    self.lexeme = lexeme
                    self.utf16Offset = utf16Offset
                }
            }

            \(access)enum ParseError: Error, LocalizedError, Sendable {
                case lexical(offset: Int, text: String)
                case unexpected(token: String, state: Int, expected: [String])
                case invalidTable(String)

                \(access)var errorDescription: String? {
                    switch self {
                    case .lexical(let offset, let text):
                        "No lexer rule matches ‘\\(text)’ at UTF-16 offset \\(offset)."
                    case .unexpected(let token, let state, let expected):
                        "Unexpected ‘\\(token)’ in I\\(state); expected \\(expected.joined(separator: ", "))."
                    case .invalidTable(let message): message
                    }
                }
            }

            \(access)static func parse(_ source: String) throws -> Node {
                try parse(tokens: tokenize(source))
            }

            \(access)static func parse(tokens: [Token]) throws -> Node {
                let input = tokens + [Token(kind: "$", lexeme: "", utf16Offset: sourceEnd(tokens))]
                var cursor = 0
                var states = [0]
                var nodes: [Node] = []
                while true {
                    guard let state = states.last else { throw ParseError.invalidTable("Parser state stack is empty.") }
                    let lookahead = input[cursor]
                    guard let action = table[Cell(state: state, symbol: lookahead.kind)] else {
                        let expected = table.compactMap { cell, candidate -> String? in
                            guard cell.state == state else { return nil }
                            if case .goTo = candidate { return nil }
                            return cell.symbol
                        }.sorted()
                        throw ParseError.unexpected(token: lookahead.lexeme, state: state, expected: expected)
                    }
                    switch action {
                    case .shift(let target):
                        states.append(target)
                        nodes.append(Node(symbol: lookahead.kind, lexeme: lookahead.lexeme, utf16Offset: lookahead.utf16Offset))
                        cursor += 1
                    case .reduce(let id):
                        guard let production = productions[id], production.count < states.count,
                              production.count <= nodes.count else {
                            throw ParseError.invalidTable("Invalid reduction r\\(id).")
                        }
                        let children = production.count == 0 ? [] : Array(nodes.suffix(production.count))
                        if production.count > 0 {
                            states.removeLast(production.count)
                            nodes.removeLast(production.count)
                        }
                        guard let from = states.last,
                              case .goTo(let target)? = table[Cell(state: from, symbol: production.lhs)] else {
                            throw ParseError.invalidTable("Missing goto for \\(production.lhs).")
                        }
                        states.append(target)
                        nodes.append(Node(symbol: production.lhs, children: children))
                    case .accept:
                        guard let root = nodes.last else { throw ParseError.invalidTable("Accepted without a parse tree.") }
                        return root
                    case .goTo:
                        throw ParseError.invalidTable("A goto action appeared in the ACTION table.")
                    }
                }
            }

            \(access)static func tokenize(_ source: String) throws -> [Token] {
                guard !lexerRules.isEmpty else { return try whitespaceTokens(source) }
                let text = source as NSString
                var offset = 0
                var tokens: [Token] = []
                while offset < text.length {
                    var best: (rule: LexerRule, length: Int)?
                    for rule in lexerRules {
                        let range = NSRange(location: offset, length: text.length - offset)
                        guard let expression = try? NSRegularExpression(pattern: "(?:\\(rule.pattern))"),
                              let match = expression.firstMatch(in: source, options: [.anchored], range: range),
                              match.range.length > 0 else { continue }
                        if best == nil || match.range.length > best!.length {
                            best = (rule, match.range.length)
                        }
                    }
                    guard let best else {
                        let length = max(1, text.rangeOfComposedCharacterSequence(at: offset).length)
                        throw ParseError.lexical(offset: offset, text: text.substring(with: NSRange(location: offset, length: length)))
                    }
                    if let kind = best.rule.kind {
                        tokens.append(Token(kind: kind, lexeme: text.substring(with: NSRange(location: offset, length: best.length)), utf16Offset: offset))
                    }
                    offset += best.length
                }
                return tokens
            }

            private struct Cell: Hashable { let state: Int; let symbol: String }
            private enum Action { case shift(Int), reduce(Int), accept, goTo(Int) }
            private struct Production { let lhs: String; let count: Int }
            private struct LexerRule { let kind: String?; let pattern: String }

            private static let productions: [Int: Production] = [
        \(productions)
            ]
            private static let table: [Cell: Action] = [
        \(actionRows)
            ]
            private static let lexerRules: [LexerRule] = [
        \(rules)
            ]

            private static func whitespaceTokens(_ source: String) throws -> [Token] {
                var result: [Token] = []
                let characters = Array(source)
                var index = 0
                while index < characters.count {
                    while index < characters.count && characters[index].isWhitespace { index += 1 }
                    guard index < characters.count else { break }
                    let start = index
                    var value = ""
                    if characters[index] == "'" || characters[index] == "\\\"" {
                        let quote = characters[index]; index += 1
                        while index < characters.count && characters[index] != quote {
                            if characters[index] == "\\\\" && index + 1 < characters.count { index += 1 }
                            value.append(characters[index]); index += 1
                        }
                        guard index < characters.count else { throw ParseError.lexical(offset: start, text: value) }
                        index += 1
                    } else {
                        while index < characters.count && !characters[index].isWhitespace {
                            value.append(characters[index]); index += 1
                        }
                    }
                    result.append(Token(kind: value, utf16Offset: start))
                }
                return result
            }

            private static func sourceEnd(_ tokens: [Token]) -> Int {
                guard let token = tokens.last else { return 0 }
                return token.utf16Offset + token.lexeme.utf16.count
            }
        }
        """
    }

    private static func selectedAction(in cell: TableCell, policy: SwiftParserConflictPolicy) -> TableAction? {
        guard cell.actions.count > 1 else { return cell.actions.first }
        switch policy {
        case .fail, .firstAction: return cell.actions.first
        case .preferShift:
            return cell.actions.first { if case .shift = $0 { true } else { false } } ?? cell.actions.first
        case .preferReduce:
            return cell.actions.first { if case .reduce = $0 { true } else { false } } ?? cell.actions.first
        }
    }

    private static func lexerRules(_ grammar: ParsedGrammar) -> [(kind: String?, pattern: String)] {
        guard !grammar.lexerRules.isEmpty else { return [] }
        var result = grammar.lexerRules.map { ($0.token, $0.pattern) }
        let patterned = Set(grammar.lexerRules.compactMap(\.token))
        for terminal in grammar.terminals where terminal != "$" && !patterned.contains(terminal) {
            result.append((terminal, NSRegularExpression.escapedPattern(for: terminal)))
        }
        return result
    }

    private static func key(_ cell: CellID) -> String {
        "Cell(state: \(cell.state.rawValue), symbol: \(literal(cell.symbol)))"
    }

    private static func actionSource(_ action: TableAction) -> String {
        switch action {
        case .shift(let state): ".shift(\(state.rawValue))"
        case .reduce(let production): ".reduce(\(production.rawValue))"
        case .accept: ".accept"
        case .goTo(let state): ".goTo(\(state.rawValue))"
        }
    }

    private static func literal(_ value: String) -> String { value.debugDescription }

    private static func isValidIdentifier(_ value: String) -> Bool {
        guard let first = value.unicodeScalars.first,
              CharacterSet.letters.union(CharacterSet(charactersIn: "_")).contains(first),
              value.unicodeScalars.dropFirst().allSatisfy({
                  CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_")).contains($0)
              }) else { return false }
        return !swiftKeywords.contains(value)
    }

    private static let swiftKeywords: Set<String> = [
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func",
        "import", "init", "inout", "internal", "let", "open", "operator", "private",
        "precedencegroup", "protocol", "public", "rethrows", "static", "struct", "subscript",
        "typealias", "var", "break", "case", "continue", "default", "defer", "do", "else",
        "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch", "where", "while"
    ]
}
