import Foundation

public enum SwiftParserAccessLevel: String, CaseIterable, Codable, Sendable {
    case `public`
    case `internal`
}

public enum SwiftParserConflictPolicy: String, CaseIterable, Codable, Sendable {
    /// Refuse generation when an ACTION cell still has multiple effective actions.
    case fail
    case preferShift
    case preferReduce
    case firstAction
}

public struct SwiftParserGenerationOptions: Hashable, Codable, Sendable {
    public var typeName: String
    public var accessLevel: SwiftParserAccessLevel
    public var conflictPolicy: SwiftParserConflictPolicy

    public init(
        typeName: String = "GeneratedParser",
        accessLevel: SwiftParserAccessLevel = .public,
        conflictPolicy: SwiftParserConflictPolicy = .fail
    ) {
        self.typeName = typeName
        self.accessLevel = accessLevel
        self.conflictPolicy = conflictPolicy
    }
}

public enum SwiftParserGenerationError: Error, LocalizedError, Sendable {
    case invalidTypeName(String)
    case unresolvedConflicts([String])

    public var errorDescription: String? {
        switch self {
        case .invalidTypeName(let name):
            "‘\(name)’ is not a valid Swift type name."
        case .unresolvedConflicts(let cells):
            "Parser generation requires deterministic ACTION cells. Resolve conflicts at \(cells.joined(separator: ", ")) or select an explicit conflict policy."
        }
    }
}

enum SwiftParserCodeGenerator {
    static func generate(
        grammar: ParsedGrammar,
        artifact: GrammarArtifact,
        options: SwiftParserGenerationOptions
    ) throws -> String {
        guard isValidIdentifier(options.typeName) else {
            throw SwiftParserGenerationError.invalidTypeName(options.typeName)
        }

        let conflicts = artifact.cells.filter { cell in
            cell.actions.count > 1 && cell.actions.contains { action in
                if case .goTo = action { return false }
                return true
            }
        }
        if options.conflictPolicy == .fail, !conflicts.isEmpty {
            throw SwiftParserGenerationError.unresolvedConflicts(
                conflicts.map { "I\($0.id.state.rawValue) on ‘\($0.id.symbol)’" }
            )
        }

        let access = options.accessLevel == .public ? "public " : ""
        let actionRows = artifact.cells.compactMap { cell -> String? in
            guard let action = selectedAction(in: cell, policy: options.conflictPolicy) else { return nil }
            return "        \(key(cell.id)): \(actionSource(action))"
        }.joined(separator: ",\n")
        let productions = artifact.productions.map {
            "        \($0.id.rawValue): Production(lhs: \(literal($0.lhs)), count: \($0.rhs.count))"
        }.joined(separator: ",\n")
        let rules = lexerRules(grammar).map {
            "        LexerRule(kind: \($0.kind.map(literal) ?? "nil"), pattern: \(literal($0.pattern)), mode: \(literal($0.mode)), action: \(lexerActionSource($0.action)))"
        }.joined(separator: ",\n")
        return """
        // Generated by Grammar Workbench \(GrammarWorkbenchRelease.version).
        // Algorithm: \(artifact.algorithm.rawValue). Do not edit generated tables by hand.
        import Foundation

        \(access)enum \(options.typeName) {
            \(access)struct Token: Hashable, Sendable {
                \(access)let kind: String
                \(access)let lexeme: String
                \(access)let utf16Offset: Int
                \(access)let mode: String

                \(access)init(kind: String, lexeme: String? = nil, utf16Offset: Int = 0, mode: String = "DEFAULT") {
                    self.kind = kind
                    self.lexeme = lexeme ?? kind
                    self.utf16Offset = utf16Offset
                    self.mode = mode
                }
            }

            \(access)struct Node: Hashable, Sendable {
                \(access)let symbol: String
                \(access)let children: [Node]
                \(access)let lexeme: String?
                \(access)let utf16Offset: Int?

                \(access)init(symbol: String, children: [Node] = [], lexeme: String? = nil, utf16Offset: Int? = nil) {
                    self.symbol = symbol
                    self.children = children
                    self.lexeme = lexeme
                    self.utf16Offset = utf16Offset
                }
            }

            \(access)enum ParseError: Error, LocalizedError, Sendable {
                case lexical(offset: Int, text: String)
                case unterminatedMode(String)
                case modeStackUnderflow(Int)
                case unexpected(token: String, state: Int, expected: [String])
                case invalidTable(String)

                \(access)var errorDescription: String? {
                    switch self {
                    case .lexical(let offset, let text):
                        "No lexer rule matches ‘\\(text)’ at UTF-16 offset \\(offset)."
                    case .unterminatedMode(let mode):
                        "Input ended in lexer mode ‘\\(mode)’ instead of DEFAULT."
                    case .modeStackUnderflow(let offset):
                        "Lexer mode stack underflow at UTF-16 offset \\(offset)."
                    case .unexpected(let token, let state, let expected):
                        "Unexpected ‘\\(token)’ in I\\(state); expected \\(expected.joined(separator: ", "))."
                    case .invalidTable(let message): message
                    }
                }
            }

            \(access)enum RecoveryKind: String, Hashable, Sendable {
                case deletedToken, insertedToken, synchronized
            }

            \(access)struct Diagnostic: Hashable, Sendable {
                \(access)let tokenIndex: Int
                \(access)let utf16Offset: Int
                \(access)let state: Int
                \(access)let unexpected: String
                \(access)let expected: [String]
                \(access)let message: String
                \(access)let recovery: RecoveryKind?
                \(access)let recoverySymbol: String?
                \(access)let recoveryDetail: String?
            }

            \(access)struct RecoveryResult: Hashable, Sendable {
                \(access)let node: Node?
                \(access)let diagnostics: [Diagnostic]
                \(access)let completed: Bool
            }

            \(access)static func parse(_ source: String) throws -> Node {
                try parse(tokens: tokenize(source))
            }

            \(access)static func parse(tokens: [Token]) throws -> Node {
                let input = tokens + [Token(kind: "$", lexeme: "", utf16Offset: sourceEnd(tokens))]
                var cursor = 0
                var states = [0]
                var nodes: [Node] = []
                while true {
                    guard let state = states.last else { throw ParseError.invalidTable("Parser state stack is empty.") }
                    let lookahead = input[cursor]
                    guard let action = table[Cell(state: state, symbol: lookahead.kind)] else {
                        let expected = table.compactMap { cell, candidate -> String? in
                            guard cell.state == state else { return nil }
                            if case .goTo = candidate { return nil }
                            return cell.symbol
                        }.sorted()
                        throw ParseError.unexpected(token: lookahead.lexeme, state: state, expected: expected)
                    }
                    switch action {
                    case .shift(let target):
                        states.append(target)
                        nodes.append(Node(symbol: lookahead.kind, lexeme: lookahead.lexeme, utf16Offset: lookahead.utf16Offset))
                        cursor += 1
                    case .reduce(let id):
                        guard let production = productions[id], production.count < states.count,
                              production.count <= nodes.count else {
                            throw ParseError.invalidTable("Invalid reduction r\\(id).")
                        }
                        let children = production.count == 0 ? [] : Array(nodes.suffix(production.count))
                        if production.count > 0 {
                            states.removeLast(production.count)
                            nodes.removeLast(production.count)
                        }
                        guard let from = states.last,
                              case .goTo(let target)? = table[Cell(state: from, symbol: production.lhs)] else {
                            throw ParseError.invalidTable("Missing goto for \\(production.lhs).")
                        }
                        states.append(target)
                        nodes.append(Node(symbol: production.lhs, children: children))
                    case .accept:
                        guard let root = nodes.last else { throw ParseError.invalidTable("Accepted without a parse tree.") }
                        return root
                    case .goTo:
                        throw ParseError.invalidTable("A goto action appeared in the ACTION table.")
                    }
                }
            }

            \(access)static func parseRecovering(
                _ source: String,
                maximumDiagnostics: Int = 8
            ) throws -> RecoveryResult {
                try parseRecovering(tokens: tokenize(source), maximumDiagnostics: maximumDiagnostics)
            }

            \(access)static func parseRecovering(
                tokens originalTokens: [Token],
                maximumDiagnostics: Int = 8
            ) throws -> RecoveryResult {
                var input = originalTokens + [Token(kind: "$", lexeme: "", utf16Offset: sourceEnd(originalTokens))]
                var cursor = 0
                var states = [0]
                var nodes: [Node] = []
                var diagnostics: [Diagnostic] = []
                var insertedIndices: Set<Int> = []
                var attempts: Set<String> = []
                let limit = max(1, maximumDiagnostics)

                for _ in 0..<10_000 {
                    guard let state = states.last else { return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false) }
                    let lookahead = input[cursor]
                    guard let action = table[Cell(state: state, symbol: lookahead.kind)] else {
                        let expected = table.compactMap { cell, candidate -> String? in
                            guard cell.state == state else { return nil }
                            if case .goTo = candidate { return nil }
                            return cell.symbol
                        }.sorted()
                        let unexpected = lookahead.lexeme.isEmpty ? lookahead.kind : lookahead.lexeme
                        guard diagnostics.count < limit else {
                            return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false)
                        }
                        let signature = "\\(state):\\(cursor):\\(lookahead.kind)"
                        guard attempts.insert(signature).inserted else {
                            return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false)
                        }

                        if let inserted = expected.first(where: { symbol in
                            guard symbol != "$", let candidate = table[Cell(state: state, symbol: symbol)] else { return false }
                            switch candidate {
                            case .reduce: return true
                            case .shift(let target): return table[Cell(state: target, symbol: lookahead.kind)] != nil
                            case .accept, .goTo: return false
                            }
                        }) {
                            insertedIndices = Set(insertedIndices.map { $0 >= cursor ? $0 + 1 : $0 })
                            insertedIndices.insert(cursor)
                            input.insert(Token(kind: inserted, lexeme: "", utf16Offset: lookahead.utf16Offset), at: cursor)
                            diagnostics.append(Diagnostic(
                                tokenIndex: cursor, utf16Offset: lookahead.utf16Offset, state: state,
                                unexpected: unexpected, expected: expected,
                                message: "Unexpected ‘\\(unexpected)’ in I\\(state).",
                                recovery: .insertedToken, recoverySymbol: inserted,
                                recoveryDetail: "Inserted missing ‘\\(inserted)’ before ‘\\(unexpected)’."
                            ))
                            continue
                        }

                        if lookahead.kind != "$", cursor + 1 < input.count,
                           table[Cell(state: state, symbol: input[cursor + 1].kind)] != nil {
                            let removed = input.remove(at: cursor)
                            insertedIndices = Set(insertedIndices.compactMap {
                                $0 == cursor ? nil : ($0 > cursor ? $0 - 1 : $0)
                            })
                            diagnostics.append(Diagnostic(
                                tokenIndex: cursor, utf16Offset: removed.utf16Offset, state: state,
                                unexpected: unexpected, expected: expected,
                                message: "Unexpected ‘\\(unexpected)’ in I\\(state).",
                                recovery: .deletedToken, recoverySymbol: removed.kind,
                                recoveryDetail: "Deleted ‘\\(unexpected)’ and resumed with ‘\\(input[cursor].kind)’."
                            ))
                            continue
                        }

                        if let inserted = expected.first(where: { symbol in
                            guard symbol != "$", let candidate = table[Cell(state: state, symbol: symbol)] else { return false }
                            if case .shift = candidate { return true }
                            return false
                        }) {
                            insertedIndices = Set(insertedIndices.map { $0 >= cursor ? $0 + 1 : $0 })
                            insertedIndices.insert(cursor)
                            input.insert(Token(kind: inserted, lexeme: "", utf16Offset: lookahead.utf16Offset), at: cursor)
                            diagnostics.append(Diagnostic(
                                tokenIndex: cursor, utf16Offset: lookahead.utf16Offset, state: state,
                                unexpected: unexpected, expected: expected,
                                message: "Unexpected ‘\\(unexpected)’ in I\\(state).",
                                recovery: .insertedToken, recoverySymbol: inserted,
                                recoveryDetail: "Inserted missing ‘\\(inserted)’ before ‘\\(unexpected)’."
                            ))
                            continue
                        }

                        if let synchronized = ((cursor + 1)..<input.count).first(where: {
                            table[Cell(state: state, symbol: input[$0].kind)] != nil
                        }) {
                            let count = synchronized - cursor
                            input.removeSubrange(cursor..<synchronized)
                            insertedIndices = Set(insertedIndices.compactMap {
                                if $0 >= cursor && $0 < synchronized { return nil }
                                return $0 >= synchronized ? $0 - count : $0
                            })
                            diagnostics.append(Diagnostic(
                                tokenIndex: cursor, utf16Offset: lookahead.utf16Offset, state: state,
                                unexpected: unexpected, expected: expected,
                                message: "Unexpected ‘\\(unexpected)’ in I\\(state).",
                                recovery: .synchronized, recoverySymbol: input[cursor].kind,
                                recoveryDetail: "Discarded \\(count) token(s) and synchronized at ‘\\(input[cursor].kind)’."
                            ))
                            continue
                        }

                        if states.count > 1 {
                            states.removeLast()
                            if !nodes.isEmpty { nodes.removeLast() }
                            diagnostics.append(Diagnostic(
                                tokenIndex: cursor, utf16Offset: lookahead.utf16Offset, state: state,
                                unexpected: unexpected, expected: expected,
                                message: "Unexpected ‘\\(unexpected)’ in I\\(state).",
                                recovery: .synchronized, recoverySymbol: lookahead.kind,
                                recoveryDetail: "Popped one parser state while seeking a synchronization point."
                            ))
                            continue
                        }
                        diagnostics.append(Diagnostic(
                            tokenIndex: cursor, utf16Offset: lookahead.utf16Offset, state: state,
                            unexpected: unexpected, expected: expected,
                            message: "Unexpected ‘\\(unexpected)’ in I\\(state).",
                            recovery: nil, recoverySymbol: nil, recoveryDetail: nil
                        ))
                        return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false)
                    }

                    switch action {
                    case .shift(let target):
                        states.append(target)
                        let symbol = insertedIndices.contains(cursor) ? "⟨missing \\(lookahead.kind)⟩" : lookahead.kind
                        nodes.append(Node(symbol: symbol, lexeme: lookahead.lexeme.isEmpty ? nil : lookahead.lexeme, utf16Offset: lookahead.utf16Offset))
                        cursor += 1
                    case .reduce(let id):
                        guard let production = productions[id], production.count < states.count,
                              production.count <= nodes.count else {
                            return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false)
                        }
                        let children = production.count == 0 ? [] : Array(nodes.suffix(production.count))
                        if production.count > 0 {
                            states.removeLast(production.count)
                            nodes.removeLast(production.count)
                        }
                        guard let from = states.last,
                              case .goTo(let target)? = table[Cell(state: from, symbol: production.lhs)] else {
                            return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false)
                        }
                        states.append(target)
                        nodes.append(Node(symbol: production.lhs, children: children))
                    case .accept:
                        return RecoveryResult(node: nodes.last, diagnostics: diagnostics, completed: nodes.last != nil)
                    case .goTo:
                        return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false)
                    }
                }
                return RecoveryResult(node: nil, diagnostics: diagnostics, completed: false)
            }

            \(access)static func tokenize(_ source: String) throws -> [Token] {
                guard !lexerRules.isEmpty else { return try whitespaceTokens(source) }
                let text = source as NSString
                var offset = 0
                var tokens: [Token] = []
                var modeStack = ["DEFAULT"]
                while offset < text.length {
                    let mode = modeStack.last ?? "DEFAULT"
                    var best: (rule: LexerRule, length: Int)?
                    for rule in lexerRules where rule.mode == mode {
                        let range = NSRange(location: offset, length: text.length - offset)
                        guard let expression = try? NSRegularExpression(pattern: "(?:\\(rule.pattern))"),
                              let match = expression.firstMatch(in: source, options: [.anchored], range: range),
                              match.range.length > 0 else { continue }
                        if best == nil || match.range.length > best!.length {
                            best = (rule, match.range.length)
                        }
                    }
                    guard let best else {
                        let length = max(1, text.rangeOfComposedCharacterSequence(at: offset).length)
                        throw ParseError.lexical(offset: offset, text: text.substring(with: NSRange(location: offset, length: length)))
                    }
                    if let kind = best.rule.kind {
                        tokens.append(Token(kind: kind, lexeme: text.substring(with: NSRange(location: offset, length: best.length)), utf16Offset: offset, mode: mode))
                    }
                    switch best.rule.action {
                    case .none: break
                    case .begin(let target): modeStack[modeStack.count - 1] = target
                    case .push(let target): modeStack.append(target)
                    case .pop:
                        guard modeStack.count > 1 else { throw ParseError.modeStackUnderflow(offset) }
                        modeStack.removeLast()
                    }
                    offset += best.length
                }
                guard modeStack == ["DEFAULT"] else {
                    throw ParseError.unterminatedMode(modeStack.last ?? "DEFAULT")
                }
                return tokens
            }

            private struct Cell: Hashable { let state: Int; let symbol: String }
            private enum Action { case shift(Int), reduce(Int), accept, goTo(Int) }
            private struct Production { let lhs: String; let count: Int }
            private enum LexerAction { case none, begin(String), push(String), pop }
            private struct LexerRule { let kind: String?; let pattern: String; let mode: String; let action: LexerAction }

            private static let productions: [Int: Production] = [
        \(productions)
            ]
            private static let table: [Cell: Action] = [
        \(actionRows)
            ]
            private static let lexerRules: [LexerRule] = [
        \(rules)
            ]

            private static func whitespaceTokens(_ source: String) throws -> [Token] {
                var result: [Token] = []
                let characters = Array(source)
                var index = 0
                while index < characters.count {
                    while index < characters.count && characters[index].isWhitespace { index += 1 }
                    guard index < characters.count else { break }
                    let start = index
                    var value = ""
                    if characters[index] == "'" || characters[index] == "\\\"" {
                        let quote = characters[index]; index += 1
                        while index < characters.count && characters[index] != quote {
                            if characters[index] == "\\\\" && index + 1 < characters.count { index += 1 }
                            value.append(characters[index]); index += 1
                        }
                        guard index < characters.count else { throw ParseError.lexical(offset: start, text: value) }
                        index += 1
                    } else {
                        while index < characters.count && !characters[index].isWhitespace {
                            value.append(characters[index]); index += 1
                        }
                    }
                    result.append(Token(kind: value, utf16Offset: start))
                }
                return result
            }

            private static func sourceEnd(_ tokens: [Token]) -> Int {
                guard let token = tokens.last else { return 0 }
                return token.utf16Offset + token.lexeme.utf16.count
            }
        }
        """
    }

    private static func selectedAction(in cell: TableCell, policy: SwiftParserConflictPolicy) -> TableAction? {
        guard cell.actions.count > 1 else { return cell.actions.first }
        switch policy {
        case .fail, .firstAction: return cell.actions.first
        case .preferShift:
            return cell.actions.first { if case .shift = $0 { true } else { false } } ?? cell.actions.first
        case .preferReduce:
            return cell.actions.first { if case .reduce = $0 { true } else { false } } ?? cell.actions.first
        }
    }

    private static func lexerRules(_ grammar: ParsedGrammar) -> [(kind: String?, pattern: String, mode: String, action: LexerModeAction)] {
        guard !grammar.lexerRules.isEmpty else { return [] }
        var result = grammar.lexerRules.map { ($0.token, $0.pattern, $0.mode, $0.action) }
        let patterned = Set(grammar.lexerRules.compactMap(\.token))
        for terminal in grammar.terminals where terminal != "$" && !patterned.contains(terminal) {
            result.append((terminal, NSRegularExpression.escapedPattern(for: terminal), "DEFAULT", .none))
        }
        return result
    }

    private static func lexerActionSource(_ action: LexerModeAction) -> String {
        switch action {
        case .none: ".none"
        case .begin(let mode): ".begin(\(literal(mode)))"
        case .push(let mode): ".push(\(literal(mode)))"
        case .pop: ".pop"
        }
    }

    private static func key(_ cell: CellID) -> String {
        "Cell(state: \(cell.state.rawValue), symbol: \(literal(cell.symbol)))"
    }

    private static func actionSource(_ action: TableAction) -> String {
        switch action {
        case .shift(let state): ".shift(\(state.rawValue))"
        case .reduce(let production): ".reduce(\(production.rawValue))"
        case .accept: ".accept"
        case .goTo(let state): ".goTo(\(state.rawValue))"
        }
    }

    private static func literal(_ value: String) -> String { value.debugDescription }

    private static func isValidIdentifier(_ value: String) -> Bool {
        guard let first = value.unicodeScalars.first,
              CharacterSet.letters.union(CharacterSet(charactersIn: "_")).contains(first),
              value.unicodeScalars.dropFirst().allSatisfy({
                  CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "_")).contains($0)
              }) else { return false }
        return !swiftKeywords.contains(value)
    }

    private static let swiftKeywords: Set<String> = [
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func",
        "import", "init", "inout", "internal", "let", "open", "operator", "private",
        "precedencegroup", "protocol", "public", "rethrows", "static", "struct", "subscript",
        "typealias", "var", "break", "case", "continue", "default", "defer", "do", "else",
        "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch", "where", "while"
    ]
}
